name: storage_manager
description: FireStorage & DevicePersistor Manager facilitates quick implementation in your app
version: 0.1.12
homepage: https://github.com/misdevelop-org/storage_manager

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.10
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
