name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    build:
      runs-on: ubuntu-latest
      container:
        image: google/dart:latest
      steps:
        - uses: actions/checkout@v3
#        - name: Setup credentials
#          run: |
#            mkdir -p ~/.pub-cache
#            cat <<EOF > ~/.pub-cache/credentials.json
#            {
#              "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
#              "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
#              "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
#              "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
#              "expiration": 1570721159347
#            }
#            EOF
        - name: Dart format
          run: dart format lib -l 120
        - name: Publish package
          run: pub publish -f